import styles from '../styles/Home.module.css'
import Header from "./Header";
import Footer from "./Footer";
import Head from "next/head";

const Layout = ({children}) => {
    return (
        <div className={styles.layoutStyle}>
            <Head data-testid="mainHead">
                <title>Practical Test Pyramid Server</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="shortcut icon" href="/pngegg2.png" />
            </Head>
            <Header tag_1='h3' main_title_1='REST ' tag_2='h2' main_title_2=''/>
            {children}
            <Footer />
        </div>
    );
};

export default Layout